apiVersion: v1
kind: Service
metadata:
  name: ubereats-backend-service
  labels:
    app: ubereats-backend
spec:
  type: NodePort
  selector:
    app: ubereats-backend
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 31530  # Ensure this matches the port you want to expose
