apiVersion: v1
kind: Service
metadata:
  name: ubereats-frontend-service
spec:
  type: NodePort
  selector:
    app: ubereats-frontend
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
    nodePort: 32000 # NodePort value to expose the frontend
