apiVersion: v1
kind: Service
metadata:
  name: ubereats-backend-service
spec:
  selector:
    app: ubereats-backend
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: LoadBalancer
