# Generated by Django 5.1.1 on 2024-10-25 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0005_customer_latitude_customer_longitude"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="country",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
