# Generated by Django 5.1.1 on 2024-10-25 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0006_customer_country"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customer",
            name="country",
        ),
        migrations.RemoveField(
            model_name="customer",
            name="latitude",
        ),
        migrations.RemoveField(
            model_name="customer",
            name="longitude",
        ),
    ]
