# Generated by Django 5.1.1 on 2024-10-25 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0007_remove_customer_country_remove_customer_latitude_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customer",
            name="email",
        ),
    ]
