# Use a slim Python image
FROM python:3.12-slim

# Set the working directory
WORKDIR /app

# Install system-level dependencies
RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    libpq-dev \
    libmariadb-dev-compat \
    libmariadb-dev \
    libjpeg-dev \
    zlib1g-dev \
    libssl-dev \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

# Copy the production requirements file first to leverage Docker layer caching
COPY production-requirements.txt .

# Copy the requirements file
COPY requirements.txt .

# Upgrade pip and install production Python dependencies
RUN pip install --upgrade pip && pip install --no-cache-dir -r production-requirements.txt

# Copy the application code
COPY . .

# Expose the application port
EXPOSE 8000

# Run the Django application
CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]
