# Generated by Django 5.1.1 on 2024-10-12 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="restaurant",
            name="password",
            field=models.CharField(max_length=256),
        ),
    ]
