# Generated by Django 5.1.1 on 2024-10-25 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0003_restaurant_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="restaurant",
            name="contact_info",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="restaurant",
            name="timings",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
